# Generated by Django 4.0.6 on 2022-10-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "party",
            },
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docket_date", models.DateTimeField()),
                ("docket_number", models.IntegerField()),
                ("no_of_pack", models.IntegerField()),
                ("station", models.CharField(max_length=10)),
                ("weight", models.FloatField()),
                ("rate", models.FloatField()),
                ("charge", models.FloatField()),
                ("other_charge", models.FloatField()),
                ("total", models.FloatField()),
                ("paid", models.FloatField()),
                ("dispatch", models.CharField(max_length=50)),
                ("pay_mode", models.CharField(max_length=50)),
                ("bill_status", models.CharField(max_length=50)),
                ("remarks", models.CharField(max_length=250)),
                ("cgst", models.FloatField()),
                ("sgst", models.FloatField()),
                ("igst", models.FloatField()),
                ("round_amt", models.FloatField()),
                ("type", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party",
                    models.ForeignKey(
                        db_column="party",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.party",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="Charges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lr_date", models.DateField()),
                ("dispatch_expense", models.FloatField()),
                ("dispatch_paid_on", models.DateField(blank=True, null=True)),
                ("door_delivery_expense", models.FloatField()),
                ("door_delivery_paid_on", models.DateField(blank=True, null=True)),
                ("pay_method", models.CharField(max_length=50)),
                ("any_other_expense", models.FloatField(blank=True, null=True)),
                ("any_other_expense_paid_on", models.DateField(blank=True, null=True)),
                (
                    "any_other_expense_pay_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("total", models.DecimalField(decimal_places=0, max_digits=10)),
                ("paid", models.DecimalField(decimal_places=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.documents",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        db_column="party",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.party",
                    ),
                ),
            ],
            options={
                "db_table": "charges",
            },
        ),
    ]
