# Generated by Django 4.0.6 on 2022-10-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bills",
            name="payment_received_at",
            field=models.DateField(db_index=True),
        ),
    ]
